#!/bin/bash
echo "🚀 一键推送脚本"
echo "=============="
echo ""
echo "请在GitHub创建仓库后运行此脚本。"
echo ""
echo "1. 确保已在GitHub创建："
echo "   仓库名: earth-materials-research"
echo "   描述: 《读地球的人》纪录片素材研究"
echo "   Public仓库"
echo ""
echo "2. 运行推送命令："
echo ""
echo "   cd /Users/louyanfei/.openclaw/workspace/earth-materials-research"
echo "   git push -u origin main"
echo ""
echo "3. 如果推送成功，你会看到："
echo "   * [new branch] main -> main"
echo "   Branch 'main' set up to track remote branch 'main' from 'origin'"
echo ""
echo "4. 然后启用GitHub Pages："
echo "   Settings → Pages → main branch → Save"
echo ""
echo "5. 访问在线版本："
echo "   https://wangzhprince-wq.github.io/earth-materials-research/"
echo ""
echo "🎯 项目已准备就绪，等待你的仓库创建！"
