#!/bin/bash
echo "⚡ GitHub Pages快速启用指南"
echo "=========================="
echo ""
echo "🎯 直接访问设置页面："
echo "   https://github.com/wangzhprince-wq/earth-materials-research/settings/pages"
echo ""
echo "📋 三步操作："
echo ""
echo "1. 选择 Source:"
echo "   ▼ 点击下拉菜单"
echo "   → 选择 'Deploy from a branch'"
echo ""
echo "2. 选择 Branch:"
echo "   ▼ 点击下拉菜单"  
echo "   → 选择 'main'"
echo ""
echo "3. 选择 Folder:"
echo "   ▼ 点击下拉菜单"
echo "   → 选择 '/ (root)'"
echo ""
echo "💾 最后：点击 'Save' 按钮"
echo ""
echo "⏱️ 等待1-2分钟部署完成"
echo ""
echo "🌐 访问你的网站："
echo "   https://wangzhprince-wq.github.io/earth-materials-research/"
echo ""
echo "✅ 成功后你会看到："
echo "   • 《读地球的人》纪录片素材研究标题"
echo "   • 42项免费素材统计"
echo "   • 28项参考素材分析"
echo "   • 5个脚本章节导航"
echo "   • 素材搜索功能"
echo ""
echo "🆘 如果遇到问题："
echo "   1. 确认仓库是Public"
echo "   2. 确认有index.html文件（我们有）"
echo "   3. 等待3-5分钟再试"
echo "   4. 清除浏览器缓存"
echo ""
echo "🚀 立即操作，启用你的在线素材研究平台！"
