#!/bin/bash
echo "🎬 《读地球的人》素材研究项目部署"
echo "=================================="
echo ""
echo "📁 本地项目位置："
echo "   /Users/louyanfei/.openclaw/workspace/earth-materials-research/"
echo ""
echo "✅ 项目已包含："
echo "   • index.html - 主页面"
echo "   • 42项免费素材数据库"
echo "   • 28项参考素材分析"
echo "   • 专业CSS样式"
echo "   • 使用指南文档"
echo ""
echo "🚀 部署步骤："
echo ""
echo "1. 先在GitHub创建仓库："
echo "   访问：https://github.com/wangzhprince-wq?tab=repositories"
echo "   点击 'New' → 仓库名: earth-materials-research"
echo "   描述: 《读地球的人》纪录片素材研究"
echo "   选择: Public"
echo "   不要初始化README"
echo ""
echo "2. 创建后获取仓库URL，类似："
echo "   https://github.com/wangzhprince-wq/earth-materials-research.git"
echo ""
echo "3. 运行以下命令推送："
echo ""
echo "   cd /Users/louyanfei/.openclaw/workspace/earth-materials-research"
echo "   git remote add origin https://github.com/wangzhprince-wq/earth-materials-research.git"
echo "   git push -u origin main"
echo ""
echo "4. 启用GitHub Pages："
echo "   Settings → Pages → Source: main → Save"
echo ""
echo "5. 访问在线版本："
echo "   https://wangzhprince-wq.github.io/earth-materials-research/"
echo ""
echo "🎯 立即预览本地版本："
echo "   open /Users/louyanfei/.openclaw/workspace/earth-materials-research/index.html"
echo ""
echo "📊 项目统计："
echo "   7个文件 | 42项免费素材 | 28项参考素材"
echo "   5个脚本章节 | 响应式设计 | 交互搜索"
